FROM node:20-alpine

# Create app directory and set ownership
RUN mkdir -p /app && chown -R node:node /app
WORKDIR /app

USER node

COPY --chown=node:node package.json package-lock.json* ./
RUN npm install

COPY --chown=node:node . .

CMD ["npm", "run", "dev"]
