apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 9999
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # 🚀 Registry Local de Cube Path
          image: localhost:5000/backend:latest
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apexdrive-secrets
                  key: db-password
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DB_PASSWORD)@postgres:5432/apexdrive_db"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: apexdrive-secrets
                  key: jwt-secret
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: apexdrive-secrets
                  key: gemini-api-key
            - name: MINIO_ENDPOINT
              value: "minio"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apexdrive-secrets
                  key: minio-root-password
            - name: MINIO_PUBLIC_URL
              value: "http://apexdrive.quanticarch.com/apexdrive-assets"
            - name: INITIAL_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apexdrive-secrets
                  key: initial-user-password
          ports:
            - containerPort: 9999
