apiVersion: v1
kind: Secret
metadata:
  name: apexdrive-secrets
  namespace: default
type: Opaque
stringData:
  jwt-secret: "apexdrive_super_secure_qa_token_2026"
  db-password: "apexdrive_qa_pass_SECRET"
  minio-root-password: "minio-qa-pass-SECURE"
  gemini-api-key: "AIzaSyDDHTbeuFG_VyEAAq3Qp39ewMqyytqMkLU"
  initial-user-password: "AdminQA_2026!"
